#!/usr/bin/env python3
from csvReader import CsvReader

def main():
    #Recuperation de la class CsvReader dans la variable csv
    csv = CsvReader()
    csv.read()

if __name__=="__main__":
    main()