#!/usr/bin/env python3
import sys
from csvHandler import CsvHandler

def main():
    if len(sys.argv) < 2:
        print("Please enter the csv you would parse.")
        return
    csv = CsvHandler(sys.argv[1])
    csv.handler()

if __name__=="__main__":
    main()