#!/usr/bin/env python3
import sys
from csvHandler import CsvHandler

def main():
    csv = CsvHandler(sys.argv[1])
    if len(sys.argv) < 2:
        print("Please enter the csv you would parse.")
    csv.handler(sys.argv[1])

if __name__=="__main__":
    main()