#!/usr/bin/env python3
import sys
from csvHandler import CsvWriter

def main():
    csv = CsvWriter()
    if len(sys.argv) < 2:
        print("Please enter the csv you would parse.")
    else:
        csv.write(sys.argv[1])

if __name__=="__main__":
    main()