#!/usr/bin/env python3

from csvHandler import CsvHandler
import sys
#Ici, nous ajoutons grace à la librairie sys la possibilité
# de recuperer une input clavier lors de l'execution du script

def main():
    csv = CsvHandler()


    try:
        csv.read(sys.argv[1])
    except:
        print("Please enter the csv you would parse.")

if __name__=="__main__":
    main()